name: Autonomous Agent

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  autonomous-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup GitHub CLI
        run: gh --version
          
      - name: Autonomous Agent Execution
        run: |
          echo "$(date)"
          ISSUE_COUNT=$(gh issue list --state open --json number | jq length)
          echo "issues:$ISSUE_COUNT"
          
          if [ "$ISSUE_COUNT" -gt 0 ]; then
            ISSUE_NUMBERS=$(gh issue list --state open --json number --jq '.[].number')
            for issue_num in $ISSUE_NUMBERS; do
              ISSUE_TITLE=$(gh issue view $issue_num --json title --jq '.title')
              echo "process:$issue_num:$ISSUE_TITLE"
            done
          else
            echo "status:clean"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
